#!/usr/bin/env bash
# Inspired by https://github.com/protiumx/.dotfiles

set -o errexit

. bootstrap/utils.sh

REPO_URL=https://github.com/spoohie/dotfiles.git
REPO_PATH="$HOME/repos/dotfiles"
SHARED_DOTFILES=/Users/Shared/dotfiles

install_xcode() {
    if xcode-select -p >/dev/null; then
        warn "xCode Command Line Tools already installed"
    else
        info "Installing xCode Command Line Tools..."
        xcode-select --install
        sudo xcodebuild -license accept
    fi
}

install_homebrew() {
    export HOMEBREW_CASK_OPTS="--appdir=/Applications"
    if hash brew &>/dev/null; then
        warn "Homebrew already installed"
    else
        info "Installing homebrew..."
        sudo --validate # reset `sudo` timeout to use Homebrew install in noninteractive mode
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zprofile && source ~/.zprofile
    fi
}

info "####### dotfiles #######"
read -p "Press enter to start:"
info "Bootstraping..."

install_xcode
install_homebrew

info "Installing Git"
brew install git

info "Cloning dotfiles repo from $REPO_URL into $REPO_PATH"
git clone "$REPO_URL" "$REPO_PATH"

info "Creating symlink from $REPO_PATH to $SHARED_DOTFILES"
ln -s $REPO_PATH $SHARED_DOTFILES

info "Change path to $REPO_PATH"
cd "$REPO_PATH" >/dev/null

. bootstrap/bootstrap.sh
bootstrap